
CREATE SEQUENCE seq_board;

CREATE TABLE TBL_BOARD(
	bno number(10),
	title varchar2(1000) NOT NULL,
	content varchar2(2000) NOT NULL,
	writer varchar2(100) NOT NULL,
	regdate DATE DEFAULT sysdate,
	updatedate DATE DEFAULT sysdate,
	CONSTRAINT PK_BOARD PRIMARY KEY(bno)
);

SELECT * FROM TBL_BOARD ;

SELECT COUNT(*) FROM TBL_BOARD tb ;

--더미 데이터 넣는 방

INSERT INTO TBL_BOARD (bno, title, content, writer)
values(seq_board.nextval, 'test447548', 'content75', 'user00');

INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER) 
(SELECT  SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_BOARD tb);



CREATE SEQUENCE seq_file;

CREATE TABLE TBL_FILE(
	fno number(10),
	bno number(10) NOT NULL,
	fileName varchar2(1000) NOT NULL,
	filePath varchar2(1000) NOT NULL, 
	uploadDate DATE DEFAULT sysdate,
	CONSTRAINT PK_FILE PRIMARY KEY(fno),
	CONSTRAINT FK_FILE FOREIGN KEY(bno) REFERENCES TBL_BOARD(bno) 
);

DROP TABLE tbl_file;

SELECT * FROM TBL_FILE; 

CREATE SEQUENCE SEQ_reply;

CREATE TABLE TBL_reply(
	RNO NUMBER(10),
	BNO NUMBER(10) NOT NULL,
	REPLY varchar2(2000) NOT NULL,
	REPLYer varchar2(100) NOT NULL,
	REPLYDATE DATE DEFAULT sysdate,
	updatedate DATE DEFAULT sysdate
);

ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY(RNO);
ALTER TABLE TBL_REPLY ADD CONSTRAINT FK_REPLY FOREIGN KEY(BNO) REFERENCES TBL_BOARD(BNO);

SELECT * FROM tbl_reply WHERE rno = 40;

INSERT INTO TBL_REPLY (RNO, BNO, REPLY, REPLYER) 
(SELECT  SEQ_REPLY.NEXTVAL, 385058, '이것은 댓글이', 'CONTENT' FROM TBL_REPLY tb);

SELECT * FROM TBL_REPLY tb ;